kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-status-reader
  namespace: {{ .Release.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
{{- if .Values.serviceAccountName }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-status-reader-binding
  namespace: {{ .Release.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-status-reader
{{- end }}